version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing angular cli...
      - npm install -g @angular/cli
  build:    
    commands:
      - echo build process started now
      - ng build --configuration production
artifacts:
  files:
    - dist/**/*
    - appspec.yml
    - nginx_reload.sh
