version: 0.2
phases:
  install:
    commands:
      - echo install process started 
      - npm install -g @angular/cli@11.2.2 npm@latest
  build:    
    commands:
      - echo build process started now
      - ng build --configuration production
artifacts:
  files:
    - dist/**/*
    - appspec.yml
    - nginx_reload.sh
